function testInputsTrans = transformJapData(testInputs,  shifts, scales)
testInputsTrans = cell(370,1);
for s = 1:370
    testInputsTrans{s} = ...
        [(testInputs{s}(:,1:12)  + ...
        repmat(shifts, size(testInputs{s},1), 1)) * diag(scales), ...
        testInputs{s}(:,13:14)];
end